script: 'RUBYOPT=-rubygems rake bacon'
before_script:
  - "test -s \"$HOME/.rvm/scripts/rvm\" && source \"$HOME/.rvm/scripts/rvm\""
  - "test -s .gems && rvm gemset import .gems"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - rbx
  - rbx-2.0
  - ree
  - jruby

notifications:
  email:
    - mf@rubyists.com

branches:
  only:
    - master
